"""initial migration

Revision ID: 1801ec1380e7
Revises: None
Create Date: 2016-01-16 16:39:21.327108

"""

# revision identifiers, used by Alembic.
revision = '1801ec1380e7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    ### end Alembic commands ###
